spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**

        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter

        - id: r3
          uri: http://localhost:8083/
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter

management:
  endpoints:
    web:
      exposure:
        include: "*"
